export const types = {
    SET_PAGE: "SET_PAGE",
    GO_DETAILS: "GO_DETAILS",
    GO_LOADING: "GO_LOADING",
    GO_LOADING_PLANET: 'GO_LOADING_PLANET',

    SET_GALAXY: "SET_GALAXY",
    SET_ZOOM: "SET_ZOOM",

    SHOW_TOAST: "SHOW_TOAST",
    HIDE_TOAST: "HIDE_TOAST"

};